/* Fake catalog for the MSWYSL storefront UI kit. Window global, not a module. */
window.MS_PRODUCTS = [
  { id: 'exhumed-rites-ls', artist: 'Cadaverous Bloom', title: 'Exhumed Rites Long Sleeve',
    price: 38, compareAt: 52, image: '../../assets/merch/tee-black-pink.jpg',
    badges: [{ label: 'Limited · 100', variant: 'limited' }], rating: 4.5, reviews: 128,
    type: 'Apparel', sizes: ['S','M','L','XL'], soldOut: false },
  { id: 'toxic-doom-hoodie', artist: 'Sunn Abyss', title: 'Toxic Doom Hoodie',
    price: 64, compareAt: null, image: '../../assets/merch/hood-ink-lime.jpg',
    badges: [{ label: 'New', variant: 'new' }], rating: 5, reviews: 37,
    type: 'Apparel', sizes: ['M','L','XL'], soldOut: false },
  { id: 'necrotic-split-7', artist: 'Goregrind Split', title: 'Necrotic Split 7" Vinyl',
    price: 18, compareAt: null, image: '../../assets/merch/vinyl-ink-white.jpg',
    badges: [], rating: 4, reviews: 88, type: 'Vinyl', sizes: [], soldOut: true },
  { id: 'bootleg-tee-pink', artist: 'Morbid Effigy', title: 'Bootleg Logo Tee',
    price: 30, compareAt: null, image: '../../assets/merch/tee-pink-black.jpg',
    badges: [{ label: 'New', variant: 'new' }], rating: 4.5, reviews: 54,
    type: 'Apparel', sizes: ['S','M','L','XL','XXL'], soldOut: false },
  { id: 'cavern-longsleeve', artist: 'Cavernous Throne', title: 'Cavern Doom Long Sleeve',
    price: 42, compareAt: 56, image: '../../assets/merch/longsleeve-black-pink.jpg',
    badges: [{ label: 'Limited · 50', variant: 'limited' }], rating: 5, reviews: 19,
    type: 'Apparel', sizes: ['S','M','L'], soldOut: false },
  { id: 'death-cap', artist: 'MSWYSL', title: 'Spiked Logo Cap',
    price: 28, compareAt: null, image: '../../assets/merch/cap-ink-pink.jpg',
    badges: [], rating: 4, reviews: 41, type: 'Accessories', sizes: ['OS'], soldOut: false },
  { id: 'woven-patch', artist: 'MSWYSL', title: 'Woven Logo Patch',
    price: 9, compareAt: null, image: '../../assets/merch/patch-pink-white.jpg',
    badges: [{ label: 'Pre-order', variant: 'preorder' }], rating: 5, reviews: 210,
    type: 'Accessories', sizes: [], soldOut: false },
  { id: 'black-white-tee', artist: 'Funeral Pyre', title: 'Funeral Pyre Tee',
    price: 32, compareAt: null, image: '../../assets/merch/tee-black-white.jpg',
    badges: [], rating: 4.5, reviews: 73, type: 'Apparel', sizes: ['S','M','L','XL'], soldOut: false },
];
